### ISSUE TITLE
Bulk upsert with pk fields

### ISSUE THREAD

**Issue by trifle** [ambitioninc/django-query-builder#76]
Hi,

thanks for django-manager-utils  and query-builder: both have a very nice, clean API and are very helpful!

I've come across a weird case where I have a custom (CharField) primary key and want to do a (postgres) native bulk_upsert on that. That isn't currently possible because of this line in `querybuilder/query.py`:

`all_fields = [field for field in ModelClass._meta.fields if field.column != pk_name]`

(https://github.com/ambitioninc/django-query-builder/blob/develop/querybuilder/query.py#L1198)

Is there a specific reasons why PKs aren't allowed here? Maybe because of some implementation detail of AutoFields? From some cursory testing, bulk upserts work just fine with custom PKs. I don't have a complete demonstration case, but it could look something like this:

```
class PersonModel(models.Model):
    name = models.CharField(max_length=40, primary_key=True)

bulk_upsert(User.objects.all(),
    [User(name=str(i)) for i in range(100)],
    ['name'],
    native=True)
```

**Comment by trifle** [comment]
After some more testing, it appears that the bulk upsert would only pick up existing rows but fail on new ones ... I guess non-integer PKs aren't supported by postgres after all.

**Comment by wesokes** [comment]
@trifle the latest version of querybuilder (0.14.1 #81 ) addresses the issue of upserting AutoField keys, so I am going to close this issue. If this doesn't solve the problem you are running into, feel free to reopen or make another issue. Thanks!
